import { ClassItem, TestimonialItem, FAQItem } from './types';

export const CLASS_CATEGORIES = [
  { id: 'all', name: 'Semua Kelas' },
  { id: 'general', name: 'General English' },
  { id: 'exam', name: 'IELTS/TOEFL Prep' },
  { id: 'business', name: 'Business English' },
  { id: 'kids', name: 'Kids & Teens' },
];

export const CLASSES_DATA: ClassItem[] = [
  {
    id: 'general-basic',
    title: 'Active Speaking Mastery',
    category: 'general',
    level: 'Beginner to Intermediate (A1 - B1)',
    duration: '3 Bulan (24 Sesi)',
    price: 1350000,
    originalPrice: 1500000,
    discountBadge: 'Diskon 10%',
    isBestSeller: true,
    description: 'Kuasai percakapan sehari-hari dengan percaya diri melalui metode interaktif tanpa fokus berlebih pada rumus tata bahasa yang membosankan.',
    features: [
      'Interactive Speaking Club setiap minggu',
      'Native Speaker Guest Session',
      'Modul digital & rekaman kelas lengkap',
      'Sertifikat Penyelesaian Resmi',
      'Konsultasi personal dengan tutor',
    ],
    image: 'bg-gradient-to-br from-indigo-500 to-purple-600',
    rating: 4.9,
    totalReviews: 142,
  },
  {
    id: 'exam-ielts',
    title: 'IELTS Bootcamp Target 7.0+',
    category: 'exam',
    level: 'Intermediate to Advanced (B1 - C1)',
    duration: '2 Bulan (32 Sesi)',
    price: 2450000,
    isBestSeller: true,
    description: 'Program intensif persiapan IELTS yang dirancang khusus untuk membantu Anda meraih skor minimal 7.0 untuk beasiswa atau kebutuhan kerja luar negeri.',
    features: [
      '4x Mock Test Real Exam Simulation',
      'Deep feedback gratis untuk Writing & Speaking',
      'Koleksi materi eksklusif lolos beasiswa',
      'Pembahasan Tips & Trik dari penguji bersertifikat',
      'Komunitas belajar aktif & support grup WA',
    ],
    image: 'bg-gradient-to-br from-blue-500 to-indigo-600',
    rating: 4.8,
    totalReviews: 95,
  },
  {
    id: 'exam-toefl',
    title: 'TOEFL iBT Score Guarantee',
    category: 'exam',
    level: 'Intermediate to Advanced (B1 - C1)',
    duration: '2 Bulan (24 Sesi)',
    price: 1850000,
    originalPrice: 2100000,
    discountBadge: 'Promo Khusus',
    description: 'Ujian TOEFL iBT kini terasa lebih mudah dengan pemahaman taktik cepat menganalisis soal-soal Reading, Listening, Speaking, dan Writing.',
    features: [
      '3x Simulasi Ujian berbasis komputer',
      'Analisis kelemahan skill secara detail',
      'Akses e-library materi TOEFL premium',
      'Pendampingan intensif dari pakar TOEFL',
      'Jaminan mengulang kelas gratis',
    ],
    image: 'bg-gradient-to-br from-emerald-500 to-teal-600',
    rating: 4.7,
    totalReviews: 68,
  },
  {
    id: 'business-corporate',
    title: 'Professional Business English',
    category: 'business',
    level: 'Intermediate (B1 - B2)',
    duration: '3 Bulan (20 Sesi)',
    price: 1990000,
    description: 'Tingkatkan karir profesional Anda secara global. Pelajari cara melakukan presentasi, negosiasi, penulisan email formal, dan memimpin rapat bisnis tingkat internasional.',
    features: [
      'Latihan Simulasi Rapat & Negosiasi langsung',
      'Penyusunan CV & Resume standar multinasional',
      'Panduan wawancara kerja (Interview Prep) eksklusif',
      'Feedback personal tata bahasa profesional',
      'Bahan ajar disesuaikan dengan industri Anda',
    ],
    image: 'bg-gradient-to-br from-amber-500 to-orange-600',
    rating: 4.9,
    totalReviews: 84,
  },
  {
    id: 'kids-fun',
    title: 'English Fun Adventure',
    category: 'kids',
    level: 'Kids (Usia 6 - 12 Tahun)',
    duration: '4 Bulan (32 Sesi)',
    price: 1200000,
    description: 'Membangun fondasi bahasa Inggris anak sejak dini melalui metode Edutainment yang menyenangkan seperti menyanyi, bercerita, menggambar, dan permainan interaktif.',
    features: [
      'Tutor berpengalaman ramah anak',
      'Metode belajar bermain tanpa tekanan',
      'Laporan progres bulanan untuk orang tua',
      'Kelas kecil (maksimal 6 anak untuk fokus penuh)',
      'Merchandise & hadiah menarik setiap target tercapai',
    ],
    image: 'bg-gradient-to-br from-pink-500 to-rose-600',
    rating: 5.0,
    totalReviews: 110,
  },
  {
    id: 'general-fluency',
    title: 'Executive Speaking & Pronunciation',
    category: 'general',
    level: 'Advanced (B2 - C2)',
    duration: '2 Bulan (16 Sesi)',
    price: 1650000,
    originalPrice: 1900000,
    discountBadge: 'Terbatas',
    description: 'Sempurnakan intonasi, pelafalan, dan aksen untuk terdengar lebih natural layaknya penutur asli (native-like). Sempurna bagi akademisi, eksekutif, dan pembicara publik.',
    features: [
      'Fokus mendalam pada Accent / Pronunciation',
      'Analisis rekaman suara secara berkala',
      'Materi debat argumentatif tingkat tinggi',
      'Personal pronunciation coaching',
      'Kurikulum standar Cambridge',
    ],
    image: 'bg-gradient-to-br from-cyan-500 to-blue-600',
    rating: 4.9,
    totalReviews: 53,
  },
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: 'testi-1',
    name: 'Andi Pratama',
    role: 'Software Engineer di GoTo',
    score: 5,
    text: 'Berkat kelas IELTS Bootcamp, skor IELTS saya melompat dari 5.5 ke 7.5 hanya dalam 2 bulan! Instrukturnya sangat sabar dan memberikan koreksi tulisan (writing) yang sangat praktis dan mendalam.',
    avatar: 'AP',
    classCategory: 'exam',
  },
  {
    id: 'testi-2',
    name: 'Sarah Wijaya',
    role: 'Mahasiswi Universitas Indonesia',
    score: 5,
    text: 'Awalnya saya takut sekali bicara bahasa Inggris di depan umum. Tapi di Active Speaking Mastery, suasananya seru dan tidak menghakimi. Tutor serta teman sekelas sangat mendukung. Sekarang saya aktif di debat kampus!',
    avatar: 'SW',
    classCategory: 'general',
  },
  {
    id: 'testi-3',
    name: 'Rian Kurniawan',
    role: 'Product Manager di Start-up FinTech',
    score: 5,
    text: 'Professional Business English sangat membantu saya dalam bernegosiasi dengan klien luar negeri. Materi resume and interview prep-nya juga terbukti ampuh membuat saya lolos wawancara karir impian saya.',
    avatar: 'RK',
    classCategory: 'business',
  },
  {
    id: 'testi-4',
    name: 'Amalia Siregar',
    role: 'Orang tua dari Azka (8 tahun)',
    score: 5,
    text: 'Anak saya senang sekali ikut kelas English Fun Adventure. Tutornya asyik dan sabar. Dia tidak pernah absen, bahkan sering mempraktikkan kosakata baru di rumah sambil bernyanyi. Rekomendasi banget untuk anak-anak!',
    avatar: 'AS',
    classCategory: 'kids',
  },
  {
    id: 'testi-5',
    name: 'Budi Hartono',
    role: 'Dosen & Akademisi Senior',
    score: 4,
    text: 'Executive Speaking membantu saya melatih aksen dan menyusun kalimat presentasi ilmiah internasional dengan lebih berwibawa. Penggunaan intonasi profesional kini terasa sangat alami bagi saya.',
    avatar: 'BH',
    classCategory: 'general',
  },
];

export const BENEFITS_DATA = [
  {
    title: 'Kurikulum Berbasis Kompetensi CEFR',
    description: 'Materi kami standar internasional (A1 sampai C2) yang relevan untuk kebutuhan karir, akademik, dan kehidupan sehari-hari.',
    icon: 'Briefcase',
    color: 'emerald',
  },
  {
    title: 'Tutor Tersertifikasi & Native Speaker',
    description: 'Belajar dibimbing oleh akademisi profesional bersertifikat TESOL/TEFL serta penguji berlisensi resmi IELTS/TOEFL.',
    icon: 'Award',
    color: 'violet',
  },
  {
    title: 'Model Belajar Hybrid & Interaktif',
    description: 'Metode komunikatif interaktif 20% teori dan 80% praktik langsung yang melatih kepercayaan diri mengobrol sejak hari pertama.',
    icon: 'MessageSquare',
    color: 'amber',
  },
  {
    title: 'Jaminan Mengulang Kelas (Garansi)',
    description: 'Kami berkomitmen penuh pada kesuksesan Anda. Jika target skor atau progres belum tercapai, Anda bebas mengulang kelas GRATIS!',
    icon: 'ShieldCheck',
    color: 'blue',
  },
];

export const FAQS_DATA: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'Apakah kelas diadakan secara online atau offline?',
    answer: 'Kami menyediakan kedua opsi tersebut! Kelas online berlangsung via video konferensi interaktif (Zoom/GMeet HD) dengan whiteboard digital. Sedangkan kelas offline diadakan di cabang kami yang modern dengan fasilitas lab bahasa terlengkap.',
  },
  {
    id: 'faq-2',
    question: 'Bagaimana cara menentukan kelas yang cocok untuk tingkat kemampuan saya?',
    answer: 'Setiap calon siswa dipersilakan mengikuti Placement Test (Tes Penempatan Tingkat) secara GRATIS di platform kami sebelum pendaftaran dimulai. Tim akademik kami juga siap mendiskusikan opsi terbaik sesuai target Anda.',
  },
  {
    id: 'faq-3',
    question: 'Apakah jadwal belajarnya fleksibel?',
    answer: 'Ya! Untuk mengakomodasi kesibukan Anda, kami menyediakan jadwal pagi, siang, sore, dan malam hari (Executive Class). Anda juga dapat memilih kelas reguler (2-3 kali seminggu) maupun kelas intensif akhir pekan.',
  },
  {
    id: 'faq-4',
    question: 'Bagaimana sistem pembayaran kursus?',
    answer: 'Pembayaran dapat dilakukan melalui Transfer Bank, E-Wallet (Gopay, OVO, ShopeePay), Kartu Kredit, atau cicilan 0% tanpa kartu kredit menggunakan platform mitra aman kami.',
  },
  {
    id: 'faq-5',
    question: 'Apakah ada sertifikat kelulusan setelah kelas berakhir?',
    answer: 'Sangat ada! Siswa yang lulus evaluasi akhir pekan dan memenuhi kehadiran minimal 80% akan mendapatkan Sertifikat Kecakapan Resmi Elektronik (E-Certificate) serta laporan perkembangan belajar personal.',
  },
];
